# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d2e109c69eb6b2900c49555f3e287123ed91eb973cb30b5469f56e92e7ab502421d257fbc033098235c827bcfb7e5ad86cede886609b01f8f73b7b4d99e3f01

test:
  secret_key_base: a439fc2dcacecd552497e47b6e0775b5e9e6260022092f08e5fc6f8d0d98dcee1d0e8a0b805d4b64d751a13ee743b71f8d062426f8f0a4744862bd70dbb30b55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
